version: 1.0.{build}
image: Ubuntu2004
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
build: off
install:
    - docker info
    - docker pull golang:1.15
    - ls /var/lib/docker
    - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sh"
    - nvm
    - gvm
build_script:
    - docker info
