version: 1.0.{build}
image: Ubuntu2004
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
build: off
cache:
    - /var/lib/docker
install:
    - yarn cache dir
    - docker info
    - nvm
    - gvm
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - docker pull golang:1.15
build_script:
    - docker info
