version: 1.0.{build}
image: Ubuntu2004
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
build: off
cache:
    - /var/lib/docker
    - /home/appveyor/.cache/yarn/v6
    - /home/appveyor/.nuget/packages
build_script:
    - cd bench
    - dotnet run -c Release -p tool -- --task build
    - dotnet run -c Release -p tool -- --task test
    - dotnet run -c Release -p tool -- --task bench
    - cd ../website
    - yarn content
    - yarn generate
artifacts:
    - path: bench/build
      name: benchmark
    - path: website/dist
      name: website
