version: 1.0.{build}
image: Ubuntu2004
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
build: off
cache:
    - /var/lib/docker
    - /home/appveyor/.cache/yarn/v6
    - /home/appveyor/.nuget/packages
install:
    - yarn cache dir
    # - docker info
    - nvm use 12
    - node -v
    - nvm use 15
    - node -v
    - nvm use 14
    - node -v
    - rvm
    - rvm use 2.7
    - ruby -v
    - which javac
    - javac -version
    - which java
    - java -version
    - csc -version
    - which csc
    - mono -V
    - which mono
    - clang-11 --version
    - clang-10 --version
    - clang-9 --version
    - clang --version
    # - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # - docker pull golang:1.15
build_script:
    - nvm use 14
    - node -v
